### ISSUE TITLE
Cannot login to pixiv.moe

### ISSUE THREAD

**Issue by Quackdoc** [LoveLiveSunshine/pixiv.moe#103]
When I try to login I get an error 

"User is not exist"

I have confirmed that my login info is correct by using a password manager to ensure the same inputs to pixiv and the app

When I click register I get 

"Request failed with status code 500"

**Comment by kokororin** [comment]
Please register first, this is not `pixiv.net`

**Comment by Quackdoc** [comment]
As I said I cannot register either.

> When I click register I get
> "Request failed with status code 500"

**Comment by kokororin** [comment]
Already fixed.
