### ISSUE TITLE
I am sorry but I got 401 error when I call /ranking API

### ISSUE THREAD

**Issue by Hatsunespica** [LoveLiveSunshine/pixiv.moe#109]
Hi!

 I know this is a silly question but I tried it with one hour and still not working T_T.
I followed the API doc and wrote the code below:
```
WEBSITE="https://api.pixiv.moe"

def getAuthorization():
    r=requests.get(WEBSITE+"/session", headers={"Content-Type":"text"})
    return r.json()

def getRanking(page, authorization):
    r=requests.get(WEBSITE+"/v2/ranking?page="+str(page)
                   ,headers=authorization)
    print(r.json())

response=getAuthorization()
getRanking(1,{'Authorization':("access_token "+response["response"]["access_token"])})
```
However, every time it returns me 401. It's frustrated and I don't know where I did things wrong. 
I also tried:
```
    r=requests.get(WEBSITE+"/v2/ranking?page="+str(page),
                   ,auth=HTTPBasicAuth(myPixivUsername, myPixivPassword),
                   ,headers=authorization)
```
not working neither.

May I ask what's the correct header format 0w0?
Thanks for your help!

**Comment by kokororin** [comment]
The Community API (this repository) is not maintained any more.
If you want to use api in your code, register an account on pixiv.moe. The correct header just discovered in Chrome Developer Tools.
