### ISSUE TITLE
Doesn’t show all pictures

### ISSUE THREAD

**Issue by desufikator** [LoveLiveSunshine/pixiv.moe#110]
Hello, I have just bought the premium and discovered several issues:
•typing several tags doesn’t properly work (shows part of images)
•function ranking doesn’t work with multiple tags 
• not all images shows properly 

I am just asking is pixiv.moe will be improved or the project is closed ?Thanks!

**Comment by kokororin** [comment]
Hi desufikator,
Could you please post your questions with detail infomation or some screenshots on email or telegram? Thanks.
