### ISSUE TITLE
API returns 400 errors so that I can't use any features

### ISSUE THREAD

**Issue by KnightChaser** [LoveLiveSunshine/pixiv.moe#111]
I installed the latest release distribution and successfully finished `npm start` without any errors.
But when the tab opens, it continuously says "Failed to load" because the API keeps returning status **400** errors with similar messages like:
```
{"code":400,"status":"failure","message":"無効なリクエスト","messages":["無効なリクエスト","Invalid request"],"response":null}
```

![image](https://user-images.githubusercontent.com/47494005/190863602-4ac1c746-430a-4a7f-8d3f-cb4bca0fa738.png)

Is it just an error case that especially corresponds to me?

**Comment by kokororin** [comment]
duplicated as #109
