### ISSUE TITLE
Have you ever published the source code for api.pixiv.moe?

### ISSUE THREAD

**Issue by bunny-girl** [LoveLiveSunshine/pixiv.moe#21]
And could I just make use of it directly (non-commercial)?
In fact, I'd rather find out how you make it, rebuild it if no existing package published and integrate into my own API server, to avoid additional pressure on your API server.

**Comment by kokororin** [comment]
Not open source.
Just based on [pixiv-api](https://github.com/topics/pixiv-api), it is easy to implement.
