### ISSUE TITLE
HTML and Service Worker does not contain same content

### ISSUE THREAD

**Issue by simon300000** [LoveLiveSunshine/pixiv.moe#22]
Output of `curl https://pixiv.moe/` and` curl https://pixiv.moe/index.html`:

➜  ~ curl https://pixiv.moe/
<!doctype html><html><head><meta charset="utf-8"><title>pixivギャラリー</title><link rel="manifest" href="/manifest.json"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="pixiv.moe - pixivギャラリー - pixiv写真の壁"><meta name="keywords" content="pixiv,pixivギャラリー,pixiv写真の壁,pixiv lovelive,lovelive,ラブライブ,μ's,Aqours,高坂穂乃果,絢瀬絵里,南ことり,園田海未,星空凛,西木野真姫,東條希,小泉花陽,矢澤にこ,綺羅ツバサ,統堂英玲奈,優木あんじゅ,高海千歌,桜内梨子,松浦果南,黒澤ダイヤ,渡辺曜,津島善子,国木田花丸,小原鞠莉,黒澤ルビィ"><meta name="google-site-verification" content="aHrpJZ8M_WPQb07omJ2bwC2fg2DQMgFFEovu9wsSD0E"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="applicable-device" content="mobile"><link rel="dns-prefetch" href="//api.pixiv.moe"><link rel="dns-prefetch" href="//www.pixiv.net"><link rel="shortcut icon" href="/assets/favicon.ico?v=1.11.4" type="image/x-icon"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png?v=1.11.4"><link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-touch-icon-57x57.png?v=1.11.4"><link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png?v=1.11.4"><link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-touch-icon-76x76.png?v=1.11.4"><link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png?v=1.11.4"><link rel="apple-touch-icon" sizes="120x120" href="/assets/apple-touch-icon-120x120.png?v=1.11.4"><link rel="apple-touch-icon" sizes="144x144" href="/assets/apple-touch-icon-144x144.png?v=1.11.4"><link rel="apple-touch-icon" sizes="152x152" href="/assets/apple-touch-icon-152x152.png?v=1.11.4"><link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon-180x180.png?v=1.11.4"><style>.message{text-align:center;padding:20px 0;color:#999}.message p{font-size:15px}</style><style>#index-loading{position:absolute;width:300px;height:100px;top:0;right:0;bottom:0;left:0;margin:auto}#index-loading p{font-size:30px!important;margin:0!important;line-height:0!important}</style></head><body><noscript><div class="message"><p>Javascriptが無効になっていると、サイト内の一部機能がご利用いただけません</p></div></noscript><div id="app"><div id="index-loading" class="message"><p><span class="progress"></span> (・ω・)<span class="wait"></span></p></div></div><script type="text/javascript">!function(){var t=setInterval(function(){var e=document.getElementById("index-loading");if(null!=e){var n=e.getElementsByClassName("wait")[0];3<n.innerHTML.length?n.innerHTML="":n.innerHTML+="."}else clearInterval(t)},400)}()</script><script>"serviceWorker"in navigator&&window.addEventListener("load",function(){navigator.serviceWorker.register("/service-worker.js")})</script><script type="text/javascript" src="/app.7de0217557d90c88c572.js"></script></body></html>%                                                                       

➜  ~ curl https://pixiv.moe/index.html
<!doctype html><html><head><meta charset="utf-8"><title>pixivギャラリー</title><link rel="manifest" href="/manifest.json"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="pixiv.moe - pixivギャラリー - pixiv写真の壁"><meta name="keywords" content="pixiv,pixivギャラリー,pixiv写真の壁,pixiv lovelive,lovelive,ラブライブ,μ's,Aqours,高坂穂乃果,絢瀬絵里,南ことり,園田海未,星空凛,西木野真姫,東條希,小泉花陽,矢澤にこ,綺羅ツバサ,統堂英玲奈,優木あんじゅ,高海千歌,桜内梨子,松浦果南,黒澤ダイヤ,渡辺曜,津島善子,国木田花丸,小原鞠莉,黒澤ルビィ"><meta name="google-site-verification" content="aHrpJZ8M_WPQb07omJ2bwC2fg2DQMgFFEovu9wsSD0E"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="applicable-device" content="mobile"><link rel="dns-prefetch" href="//api.pixiv.moe"><link rel="dns-prefetch" href="//www.pixiv.net"><link rel="shortcut icon" href="/assets/favicon.ico?v=1.11.4" type="image/x-icon"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png?v=1.11.4"><link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-touch-icon-57x57.png?v=1.11.4"><link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png?v=1.11.4"><link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-touch-icon-76x76.png?v=1.11.4"><link rel="apple-touch-icon" sizes="114x114" href="/assets/apple-touch-icon-114x114.png?v=1.11.4"><link rel="apple-touch-icon" sizes="120x120" href="/assets/apple-touch-icon-120x120.png?v=1.11.4"><link rel="apple-touch-icon" sizes="144x144" href="/assets/apple-touch-icon-144x144.png?v=1.11.4"><link rel="apple-touch-icon" sizes="152x152" href="/assets/apple-touch-icon-152x152.png?v=1.11.4"><link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon-180x180.png?v=1.11.4"><style>.message{text-align:center;padding:20px 0;color:#999}.message p{font-size:15px}</style><style>#index-loading{position:absolute;width:300px;height:100px;top:0;right:0;bottom:0;left:0;margin:auto}#index-loading p{font-size:30px!important;margin:0!important;line-height:0!important}</style></head><body><noscript><div class="message"><p>Javascriptが無効になっていると、サイト内の一部機能がご利用いただけません</p></div></noscript><div id="app"><div id="index-loading" class="message"><p><span class="progress"></span> (・ω・)<span class="wait"></span></p></div></div><script type="text/javascript">!function(){var t=setInterval(function(){var e=document.getElementById("index-loading");if(null!=e){var n=e.getElementsByClassName("wait")[0];3<n.innerHTML.length?n.innerHTML="":n.innerHTML+="."}else clearInterval(t)},400)}()</script><script>"serviceWorker"in navigator&&window.addEventListener("load",function(){navigator.serviceWorker.register("/service-worker.js")})</script><script type="text/javascript" src="/app.885ee479c0bd3f6993ab.js"></script></body></html>%                                                                            

➜  ~ 

Original content of the issue:
Failed to load resource: the server responded with a status of 404 ()

https://pixiv.moe/app.7de0217557d90c88c572.js

**Comment by kirainmoe** [comment]
It works for me. Probably index.html has been cached by your browser, try to clear caches.

**Comment by kirainmoe** [comment]
The original index.html is loading `app.7de0217557d90c88c572.js`, but this site is using Service Worker feature which will register an service worker when first visit and cache the true index.html, which is loading `app.885ee479c0bd3f6993ab.js`. Safari 12- does not support service worker, so you will see Chrome works(after the second refresh), but Safari not. Will look into this issue.

**Comment by kokororin** [comment]
Latest js file is [/app.885ee479c0bd3f6993ab.js](https://pixiv.moe/app.885ee479c0bd3f6993ab.js)

**Comment by simon300000** [comment]
Safari 12.0.1 (14606.2.104.1.1)
There is some problem with my Safari, Safari does support service worker but it does not load at `https://pixiv.moe` for some reason.
I switched to `https://pixiv.moe/index.html` it load the correct js.

我现在感觉我是个假的程序员

**Comment by kokororin** [comment]
Should be same now

**Comment by simon300000** [comment]
Oh yea

**Comment by simon300000** [comment]
I found that pages such as https://pixiv.moe/illust/71178164 will be 404 at Safari or curl, but good with Chrome.

The server side render will be useless...

**Comment by kokororin** [comment]
Forget to change the nginx config file (；￣Д￣）
It works now （＞д＜）

**Comment by simon300000** [comment]
Wohaha
