### ISSUE TITLE
可以帮忙部署下么一直报错

### ISSUE THREAD

**Issue by 20020314** [LoveLiveSunshine/pixiv.moe#26]

**Comment by kirainmoe** [comment]
It is impossible for developers to find out your problem by saying "error occurred" but providing no description.   
Please post something useful info like error logs or screenshots.

*[ryanhanwu/How-To-Ask-Questions-The-Smart-Way](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)
