### ISSUE TITLE
only one page would be shown except the ranking list

### ISSUE THREAD

**Issue by www1781315832** [LoveLiveSunshine/pixiv.moe#27]
It can only show only one page and it prompts "fail to load".Can you check it and fix it?Thank you.

**Comment by kirainmoe** [comment]
Pixiv senior member account the site used was outdated, thus the searching feature(ranking by popularity) can only show the illustrations of the first page.

**Comment by www1781315832** [comment]
There is a convenient way to search the most popular illustrations.You can put a space and put 10000 after the label you want to search.For example,you can search"オリジナル　10000" to find the illustrations collected by more than 10000 people without the Pixiv senior member account.Can this method solve the problem?
