### ISSUE TITLE
你好，我按照useage部署成功，但是无法连接到...

### ISSUE THREAD

**Issue by Cloudiver** [LoveLiveSunshine/pixiv.moe#7]
![tim 20170804003522](https://user-images.githubusercontent.com/22044321/28932648-d764fd94-78ac-11e7-856f-39547cd143e6.png)
如上图所示，可以打开网页，但是没有办法获取图片，求解答。

**Comment by kokororin** [comment]
是不是改了express端口号？只能用默认的，这在服务端限制了。

**Comment by Cloudiver** [comment]
没有，默认install，本地start测试可以正常显示，push后就出现这个

**Comment by kokororin** [comment]
部署域名只支持pixiv.moe和localhost等。

**Comment by Cloudiver** [comment]
二级域名不支持？

**Comment by kokororin** [comment]
其实可以打开控制台看到错误的，跨域了

**Comment by Cloudiver** [comment]
那怎么才能解决？

**Comment by kokororin** [comment]
自己反代，另外直接复制而不是fork真的大丈夫？

**Comment by Cloudiver** [comment]
第一次弄，没注意😅

**Comment by Nekoer** [comment]
这个反代该怎么搞，我反代都提示502 Bad Gateway
