### ISSUE TITLE
Pixiv has abadoned the old public API

### ISSUE THREAD

**Issue by kokororin** [LoveLiveSunshine/pixiv.moe#9]
Images hosted on `http://i([0-9]).pixiv.net` returns 403 in the list API.
Maybe the code should be changed.

new Ranking API:
http://api.pixiv.moe/v2/ranking

**Comment by TimWei** [comment]
Hi @kokororin 


新的api有一些差异

-  api v1的image_urls的large元素是提供original size的原图，api v2的image_urls的large元素则是640宽的缩图

-  api v2的meta_single_page内有pixiv.moe的original size的原图url，但当有多图时，meta_pages却是官网的url，不是pixiv.moe的资源

- 今日排名前20名内的#2 #14 #19没有显示在api v2上

**Comment by kokororin** [comment]
新版的api是app上抓包得来的，我发现app上的排行榜和web版是不一样的，这就很奇怪了。
v2的排行榜还是少了很多字段，必须昨日排名什么的也都没有。
现在把v1的api改了一下，image_urls字段直接再调用一次作品详情的api，这样图片地址是正常可用的。
